// <auto-generated />
using System;
using ChitFundManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChitFundManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319182809_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChitFundManager.Models.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AuctionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ChitGroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPayablePerMember")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalCollection")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WinnerAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WinnerMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChitGroupId");

                    b.HasIndex("WinnerMemberId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("ChitFundManager.Models.ChitGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChitGroups");
                });

            modelBuilder.Entity("ChitFundManager.Models.ChitMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChitGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasWon")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WinningAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("WinningMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChitGroupId");

                    b.HasIndex("MemberId");

                    b.ToTable("ChitMembers");
                });

            modelBuilder.Entity("ChitFundManager.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("ChitFundManager.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ChitGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChitGroupId");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ChitFundManager.Models.Auction", b =>
                {
                    b.HasOne("ChitFundManager.Models.ChitGroup", "ChitGroup")
                        .WithMany("Auctions")
                        .HasForeignKey("ChitGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChitFundManager.Models.Member", "WinnerMember")
                        .WithMany()
                        .HasForeignKey("WinnerMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChitGroup");

                    b.Navigation("WinnerMember");
                });

            modelBuilder.Entity("ChitFundManager.Models.ChitMember", b =>
                {
                    b.HasOne("ChitFundManager.Models.ChitGroup", "ChitGroup")
                        .WithMany("Members")
                        .HasForeignKey("ChitGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChitFundManager.Models.Member", "Member")
                        .WithMany("ChitMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChitGroup");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChitFundManager.Models.Payment", b =>
                {
                    b.HasOne("ChitFundManager.Models.ChitGroup", "ChitGroup")
                        .WithMany("Payments")
                        .HasForeignKey("ChitGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChitFundManager.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChitGroup");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ChitFundManager.Models.ChitGroup", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Members");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ChitFundManager.Models.Member", b =>
                {
                    b.Navigation("ChitMemberships");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
